Fix Build Issues on macOS
cvut/qtrvsim pull request #94
Opened 2023-12-16 17:39 UTC by SConaway

This PR addresses build issues in macOS. 

First, the include directories of a system `libelf` needs to use the 
`${LIBELF_INCLUDE_DIR}` variable, not just `${LIBELF_INCLUDE}`. 

Second, the `libelf` installed using homebrew doesn't define `EM_RISCV`:
```
/src/machine/programloader.cpp:62:32: error: use of undeclared identifier 'EM_RISCV'
    if (this->hdr.e_machine != EM_RISCV) {
```
It seems to be too old to include it.

2023-12-20 10:44 UTC, jdupak commented
Hi @SConaway,
thanks for raising the issue and suggesting sollution. There is one more issue we need to address: when libelf is installed (as dependency for something else) but it is unusable for us. It seems the best way would be to use https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html to check RISCV compatibility.

If you have time, feel free to look into it. Otherwise I will try to find some time to add that myself.

Anyway, thanks.

2023-12-20 10:46 UTC, jdupak requested changes

2023-12-20 10:46 UTC, jdupak commented on CMakeLists.txt
>              # Turn non-cmake library into a cmake target
Check of RISC-V symbol in the header here.

2023-12-20 17:00 UTC, SConaway commented
Yeah, I'll take care of that today or tomorrow. That'll solve the macOS build issue with `libelf` from `brew`.

2023-12-21 04:12 UTC, SConaway commented on CMakeLists.txt
> +            include(CheckSymbolExists)
Feel free to move this elsewhere

2023-12-21 04:12 UTC, SConaway commented on CMakeLists.txt
> +                set(LibElf_FOUND FALSE) # Force fallback
this way we can treat this as no system libelf and reuse the existing one

2023-12-21 04:23 UTC, SConaway commented
I've tested this on both my mac and on Fedora with `elfutils-devel` installed.

2023-12-23 16:13 UTC, jdupak approved these changes
LGTM Thank you

2023-12-23 16:15 UTC, merged